### ISSUE TITLE
Porque NewCoursesNewsletterSender  rompe los limites ?

### ISSUE THREAD

**Issue by kmiiloberrio-dev** [CodelyTV/java-ddd-skeleton#80]
Revisando un poco el codigo de [NewCoursesNewsletterSender](https://github.com/CodelyTV/java-ddd-skeleton/blob/main/src/mooc/main/tv/codely/mooc/notifications/application/send_new_courses_newsletter/NewCoursesNewsletterSender.java) me doy cuenta de que rompe los limites al usar SearchLastCoursesQuery y CoursesResponse.  

Incluso revisando el dominio de [NewCoursesNewsletter](https://github.com/CodelyTV/java-ddd-skeleton/blob/main/src/mooc/main/tv/codely/mooc/notifications/domain/NewCoursesNewsletter.java), también conoce de application.

Lo que se menciona dentro del libro CleanArchitecture, en los capítulos 16, 17, 18. Es tratar de mantener capas verticales relacionados con lo que hace el sistema (casos de uso). _Los casos de uso cambian por diferentes razones y a diferentes ritmos entre sí, por lo tanto, deben protegerse entre sí._ 

Me gustaría saber, si hay una razón del porque romper los limites en este componente, pues me encuentro estudiando todo esto y quería compartir mi preocupación.

**Comment by JavierCane** [comment]
¡Buenas!

La query `SearchLastCoursesQuery` es un DTO que se tira al Query Bus (https://github.com/CodelyTV/java-ddd-skeleton/blob/main/src/mooc/main/tv/codely/mooc/notifications/application/send_new_courses_newsletter/NewCoursesNewsletterSender.java#L36), y el `CoursesResponse` es el DTO de respuesta.

Esto es la forma de comunicarnos entre distintos subdominios o servicios. Lo explicamos en más detalle en los cursos de [Comunicación entre [micro]servicios](https://pro.codely.com/library/comunicacion-entre-microservicios-event-driven-architecture-35834/74823/about/) y también en el de [CQRS](https://pro.codely.com/library/cqrs-command-query-responsibility-segregation-29074/about/).

¡Saludos!
